// src/main/java/${basePackage?replace(".", "/")}/$(className}.java
package ${basePackage};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * ${projectName} Application
 * 
 * Main Spring Boot application class for ${projectName}.
 * Generated by ClaudeForge AI Code Generation Tool.
 * 
 * @author ClaudeForge
 * @version 1.0.0
 */
@SpringBootApplication
public class ${className} {

    public static void main(String[] args) {
        System.out.println("=================================================");
        System.out.println("    🚀 Starting ${projectName} Application");
        System.out.println("=================================================");
        
        SpringApplication.run(${className}.class, args);
        
        System.out.println("✅ ${projectName} Application started successfully!");
        System.out.println("🌐 Application URL: http://localhost:8080");
        <#if databaseType == "H2">
        System.out.println("🗄️  H2 Console: http://localhost:8080/h2-console");
        </#if>
        System.out.println("=================================================");
    }
}