// src/main/java/${basePackage?replace(".", "/")}/model/${className}.java
package ${basePackage}.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;

/**
 * ${className} Entity
 * 
 * JPA entity representing ${className} data.
 * Generated by ClaudeForge with standard JPA annotations.
 */
@Entity
@Table(name = "${className?lower_case}s")
public class ${className} {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // @GENERATE_GETTERS_SETTERS
    
}